name: Test

on:
  pull_request:

permissions:
  statuses: write
  checks: write

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest
      - name: Publish JUnit Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: "*/build/test-results/*/*.xml"
          reporter: java-junit
          fail-on-error: true
#          TODO: Uncomment the UI test workflow when I actually have UI tests
#  ui_tests:
#    runs-on: ubuntu-latest
#    name: Run UI Tests
#    needs:
#      - validate
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: assembleDebug assembleDebugAndroidTest
#      - name: Grant execute permission for flank_auth.sh
#        run: chmod +x flank_auth.sh
#      - name: Add auth for flank
#        env:
#          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
#        run: |
#          ./flank_auth.sh
#      - name: Run UI tests
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: runFlank